machine:
  node:
    version: 7.5.0
dependencies:
  pre:
    - npm install npm@latest -g # Should fix bug in ng test
    - npm install angular-cli@latest -g
    - npm build
test:
  override:
    - npm run test -- --single-run