# Build matrix
language: node_js
matrix:
  include:

    # Lint only in Node.js 0.12
    - node_js: '0.12'
      env: MODE=lint

    # Pa11y check only in Node.js 4.x
    - node_js: '4'
      env: MODE=pa11y
      (etc...)

    # Run tests in Node.js 4.x
    - node_js: '4'
      (etc...)

    # Run tests in Node.js 6.x
    - node_js: '6'
      (etc...)

# Build script
script:
  - 'if [ $MODE == "lint" ]; then make lint; fi'
  - 'if [ $MODE == "pa11y" ]; then make start & sleep 5; make test-pa11y; fi'
  - 'if [ ! $MODE ]; then make test; fi'